<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Product;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Concrete\Package\CommunityStore\Src\CommunityStore\Product\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'priceAdjustment', 'weightAdjustment', 'variation', 'pID', 'cID', 'pName', 'pSKU', 'pBarcode', 'pDesc', 'pDetail', 'pPrice', 'pWholesalePrice', 'pSalePrice', 'pSaleStart', 'pSaleEnd', 'pCustomerPrice', 'pPriceMaximum', 'pPriceMinimum', 'pPriceSuggestions', 'pQuantityPrice', 'pFeatured', 'pQty', 'pQtyUnlim', 'pDateAvailableStart', 'pDateAvailableEnd', 'pOutOfStockMessage', 'pAddToCartText', 'pBackOrder', 'pNoQty', 'pAllowDecimalQty', 'pQtySteps', 'pQtyLabel', 'pMaxQty', 'pTaxClass', 'pTaxable', 'pfID', 'pActive', 'pDateAdded', 'pShippable', 'pWidth', 'pHeight', 'pStackedHeight', 'pLength', 'pWeight', 'pNumberItems', 'pSeperateShip', 'pPackageData', 'pCreateUserAccount', 'pAutoCheckout', 'pOrderCompleteCID', 'pExclusive', 'pVariations', 'pNotificationEmails', 'manufacturer', 'locations', 'groups', 'files', 'images', 'userGroups', 'options', 'related', 'priceTiers', 'variations', 'discountRules', 'discountRuleIDs'];
        }

        return ['__isInitialized__', 'priceAdjustment', 'weightAdjustment', 'variation', 'pID', 'cID', 'pName', 'pSKU', 'pBarcode', 'pDesc', 'pDetail', 'pPrice', 'pWholesalePrice', 'pSalePrice', 'pSaleStart', 'pSaleEnd', 'pCustomerPrice', 'pPriceMaximum', 'pPriceMinimum', 'pPriceSuggestions', 'pQuantityPrice', 'pFeatured', 'pQty', 'pQtyUnlim', 'pDateAvailableStart', 'pDateAvailableEnd', 'pOutOfStockMessage', 'pAddToCartText', 'pBackOrder', 'pNoQty', 'pAllowDecimalQty', 'pQtySteps', 'pQtyLabel', 'pMaxQty', 'pTaxClass', 'pTaxable', 'pfID', 'pActive', 'pDateAdded', 'pShippable', 'pWidth', 'pHeight', 'pStackedHeight', 'pLength', 'pWeight', 'pNumberItems', 'pSeperateShip', 'pPackageData', 'pCreateUserAccount', 'pAutoCheckout', 'pOrderCompleteCID', 'pExclusive', 'pVariations', 'pNotificationEmails', 'manufacturer', 'locations', 'groups', 'files', 'images', 'userGroups', 'options', 'related', 'priceTiers', 'variations', 'discountRules', 'discountRuleIDs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLocations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocations', []);

        return parent::getLocations();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', []);

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', []);

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedProducts', []);

        return parent::getRelatedProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceTiers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceTiers', []);

        return parent::getPriceTiers();
    }

    /**
     * {@inheritDoc}
     */
    public function getVariations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariations', []);

        return parent::getVariations();
    }

    /**
     * {@inheritDoc}
     */
    public function clearDiscountRules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearDiscountRules', []);

        return parent::clearDiscountRules();
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscountRules($rules)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscountRules', [$rules]);

        return parent::addDiscountRules($rules);
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscountRule($discountRule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscountRule', [$discountRule]);

        return parent::addDiscountRule($discountRule);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountRules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountRules', []);

        return parent::getDiscountRules();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceAdjustment($adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceAdjustment', [$adjustment]);

        return parent::setPriceAdjustment($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceAdjustment($discounts = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceAdjustment', [$discounts]);

        return parent::getPriceAdjustment($discounts);
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightAdjustment($adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightAdjustment', [$adjustment]);

        return parent::setWeightAdjustment($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightAdjustment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightAdjustment', []);

        return parent::getWeightAdjustment();
    }

    /**
     * {@inheritDoc}
     */
    public function setVariation($variation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVariation', [$variation]);

        return parent::setVariation($variation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVariation', []);

        return parent::removeVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialVariation', []);

        return parent::setInitialVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function getVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariation', []);

        return parent::getVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectionID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectionID', [$cID]);

        return parent::setCollectionID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setSKU($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSKU', [$sku]);

        return parent::setSKU($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarcode', []);

        return parent::getBarcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarcode($barcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarcode', [$barcode]);

        return parent::setBarcode($barcode);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setDetail($detail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetail', [$detail]);

        return parent::setDetail($detail);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setWholesalePrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWholesalePrice', [$price]);

        return parent::setWholesalePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setSalePrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalePrice', [$price]);

        return parent::setSalePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPrice($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPrice', [$bool]);

        return parent::setCustomerPrice($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceMaximum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceMaximum', []);

        return parent::getPriceMaximum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceMaximum($pPriceMaximum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceMaximum', [$pPriceMaximum]);

        return parent::setPriceMaximum($pPriceMaximum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceMinimum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceMinimum', []);

        return parent::getPriceMinimum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceMinimum($pPriceMinimum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceMinimum', [$pPriceMinimum]);

        return parent::setPriceMinimum($pPriceMinimum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceSuggestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceSuggestions', []);

        return parent::getPriceSuggestions();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceSuggestionsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceSuggestionsArray', []);

        return parent::getPriceSuggestionsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceSuggestions($priceSuggestions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceSuggestions', [$priceSuggestions]);

        return parent::setPriceSuggestions($priceSuggestions);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFeatured($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFeatured', [$bool]);

        return parent::setIsFeatured($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setQty($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQty', [$qty]);

        return parent::setQty($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUnlimited($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUnlimited', [$bool]);

        return parent::setIsUnlimited($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAvailableStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAvailableStart', []);

        return parent::getDateAvailableStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAvailableStart($pDateAvailableStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAvailableStart', [$pDateAvailableStart]);

        return parent::setDateAvailableStart($pDateAvailableStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAvailableEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAvailableEnd', []);

        return parent::getDateAvailableEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAvailableEnd($dateAvailableEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAvailableEnd', [$dateAvailableEnd]);

        return parent::setDateAvailableEnd($dateAvailableEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutOfStockMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutOfStockMessage', []);

        return parent::getOutOfStockMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutOfStockMessage($outOfStockMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutOfStockMessage', [$outOfStockMessage]);

        return parent::setOutOfStockMessage($outOfStockMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddToCartText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddToCartText', []);

        return parent::getAddToCartText();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddToCartText($pAddToCartText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddToCartText', [$pAddToCartText]);

        return parent::setAddToCartText($pAddToCartText);
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowBackOrder($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowBackOrder', [$bool]);

        return parent::setAllowBackOrder($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoQty($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoQty', [$bool]);

        return parent::setNoQty($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPID()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPID();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPID', []);

        return parent::getPID();
    }

    /**
     * {@inheritDoc}
     */
    public function setPID($pID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPID', [$pID]);

        return parent::setPID($pID);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowDecimalQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowDecimalQty', []);

        return parent::getAllowDecimalQty();
    }

    /**
     * {@inheritDoc}
     */
    public function allowDecimalQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowDecimalQuantity', []);

        return parent::allowDecimalQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowDecimalQty($pAllowDecimalQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowDecimalQty', [$pAllowDecimalQty]);

        return parent::setAllowDecimalQty($pAllowDecimalQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtySteps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtySteps', []);

        return parent::getQtySteps();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtySteps($pQtySteps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtySteps', [$pQtySteps]);

        return parent::setQtySteps($pQtySteps);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtyLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtyLabel', []);

        return parent::getQtyLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtyLabel($pQtyLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtyLabel', [$pQtyLabel]);

        return parent::setQtyLabel($pQtyLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxQty', []);

        return parent::getMaxQty();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxQty($pMaxQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxQty', [$pMaxQty]);

        return parent::setMaxQty($pMaxQty);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxClass($taxClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxClass', [$taxClass]);

        return parent::setTaxClass($taxClass);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTaxable($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTaxable', [$bool]);

        return parent::setIsTaxable($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageID($fID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageID', [$fID]);

        return parent::setImageID($fID);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$bool]);

        return parent::setIsActive($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', [$date]);

        return parent::setDateAdded($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsShippable($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsShippable', [$bool]);

        return parent::setIsShippable($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeparateShip($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeparateShip', [$bool]);

        return parent::setSeparateShip($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeperateShip($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeperateShip', [$bool]);

        return parent::setSeperateShip($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageData', []);

        return parent::getPackageData();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackageData($pPackageData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackageData', [$pPackageData]);

        return parent::setPackageData($pPackageData);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeparateShip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeparateShip', []);

        return parent::getSeparateShip();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeperateShip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeperateShip', []);

        return parent::getSeperateShip();
    }

    /**
     * {@inheritDoc}
     */
    public function isSeparateShip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSeparateShip', []);

        return parent::isSeparateShip();
    }

    /**
     * {@inheritDoc}
     */
    public function isSeperateShip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSeperateShip', []);

        return parent::isSeperateShip();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', [$width]);

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', [$height]);

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function setStackedHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStackedHeight', [$height]);

        return parent::setStackedHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function setLength($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLength', [$length]);

        return parent::setLength($length);
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', [$weight]);

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberItems($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberItems', [$number]);

        return parent::setNumberItems($number);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatesUserAccount($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatesUserAccount', [$bool]);

        return parent::setCreatesUserAccount($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoCheckout($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoCheckout', [$bool]);

        return parent::setAutoCheckout($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderCompleteCID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderCompleteCID', []);

        return parent::getOrderCompleteCID();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderCompleteCID($orderCompleteCID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderCompleteCID', [$orderCompleteCID]);

        return parent::setOrderCompleteCID($orderCompleteCID);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExclusive($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExclusive', [$bool]);

        return parent::setIsExclusive($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setHasVariations($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasVariations', [$bool]);

        return parent::setHasVariations($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationEmails', []);

        return parent::getNotificationEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationEmailsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationEmailsArray', []);

        return parent::getNotificationEmailsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationEmails($pNotificationEmails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationEmails', [$pNotificationEmails]);

        return parent::setNotificationEmails($pNotificationEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturer', []);

        return parent::getManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturer($manufacturer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturer', [$manufacturer]);

        return parent::setManufacturer($manufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function setStockLevel($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockLevel', [$qty]);

        return parent::setStockLevel($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function updateProductQty($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateProductQty', [$qty]);

        return parent::updateProductQty($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributes', []);

        return parent::getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setID($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setID', [$id]);

        return parent::setID($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSKU()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSKU', []);

        return parent::getSKU();
    }

    /**
     * {@inheritDoc}
     */
    public function getPageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageID', []);

        return parent::getPageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductPage', []);

        return parent::getProductPage();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesc', []);

        return parent::getDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetail', []);

        return parent::getDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function getBasePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBasePrice', []);

        return parent::getBasePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice($qty = 1, $ignoreDiscounts = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', [$qty, $ignoreDiscounts]);

        return parent::getPrice($qty, $ignoreDiscounts);
    }

    /**
     * {@inheritDoc}
     */
    public function getWholesalePriceValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWholesalePriceValue', []);

        return parent::getWholesalePriceValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getWholesalePrice($qty = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWholesalePrice', [$qty]);

        return parent::getWholesalePrice($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedOriginalPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedOriginalPrice', []);

        return parent::getFormattedOriginalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedPrice', []);

        return parent::getFormattedPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedWholesalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedWholesalePrice', []);

        return parent::getFormattedWholesalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalePriceValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalePriceValue', []);

        return parent::getSalePriceValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalePrice($ignoreDiscounts = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalePrice', [$ignoreDiscounts]);

        return parent::getSalePrice($ignoreDiscounts);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedSalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedSalePrice', []);

        return parent::getFormattedSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaleStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaleStart', []);

        return parent::getSaleStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaleStart($saleStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaleStart', [$saleStart]);

        return parent::setSaleStart($saleStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaleEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaleEnd', []);

        return parent::getSaleEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaleEnd($saleEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaleEnd', [$saleEnd]);

        return parent::setSaleEnd($saleEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivePrice($qty = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivePrice', [$qty]);

        return parent::getActivePrice($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedActivePrice($qty = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedActivePrice', [$qty]);

        return parent::getFormattedActivePrice($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxClassID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxClassID', []);

        return parent::getTaxClassID();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxClass', []);

        return parent::getTaxClass();
    }

    /**
     * {@inheritDoc}
     */
    public function isTaxable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTaxable', []);

        return parent::isTaxable();
    }

    /**
     * {@inheritDoc}
     */
    public function isFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFeatured', []);

        return parent::isFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function isShippable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippable', []);

        return parent::isShippable();
    }

    /**
     * {@inheritDoc}
     */
    public function allowCustomerPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowCustomerPrice', []);

        return parent::allowCustomerPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function hasQuantityPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasQuantityPrice', []);

        return parent::hasQuantityPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityPrice', []);

        return parent::getQuantityPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityPrice($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityPrice', [$bool]);

        return parent::setQuantityPrice($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getDimensions($whl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimensions', [$whl]);

        return parent::getDimensions($whl);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', []);

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', []);

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getStackedHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStackedHeight', []);

        return parent::getStackedHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLength', []);

        return parent::getLength();
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberItems', []);

        return parent::getNumberItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackages', []);

        return parent::getPackages();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageID', []);

        return parent::getImageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageObj', []);

        return parent::getImageObj();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseProductImageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseProductImageID', []);

        return parent::getBaseProductImageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseProductImageObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseProductImageObj', []);

        return parent::getBaseProductImageObj();
    }

    /**
     * {@inheritDoc}
     */
    public function hasDigitalDownload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasDigitalDownload', []);

        return parent::hasDigitalDownload();
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadFiles', []);

        return parent::getDownloadFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadFileObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadFileObjects', []);

        return parent::getDownloadFileObjects();
    }

    /**
     * {@inheritDoc}
     */
    public function createsLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createsLogin', []);

        return parent::createsLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function allowQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowQuantity', []);

        return parent::allowQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function isExclusive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExclusive', []);

        return parent::isExclusive();
    }

    /**
     * {@inheritDoc}
     */
    public function hasVariations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasVariations', []);

        return parent::hasVariations();
    }

    /**
     * {@inheritDoc}
     */
    public function isUnlimited($skipDateCheck = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUnlimited', [$skipDateCheck]);

        return parent::isUnlimited($skipDateCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function autoCheckout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'autoCheckout', []);

        return parent::autoCheckout();
    }

    /**
     * {@inheritDoc}
     */
    public function allowBackOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowBackOrders', []);

        return parent::allowBackOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function hasUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasUserGroups', []);

        return parent::hasUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroupIDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroupIDs', []);

        return parent::getUserGroupIDs();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageThumb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageThumb', []);

        return parent::getImageThumb();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockLevel', []);

        return parent::getStockLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function getQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQty', []);

        return parent::getQty();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxCartQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxCartQty', []);

        return parent::getMaxCartQty();
    }

    /**
     * {@inheritDoc}
     */
    public function isSellable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSellable', []);

        return parent::isSellable();
    }

    /**
     * {@inheritDoc}
     */
    public function getimagesobjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimagesobjects', []);

        return parent::getimagesobjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationPages', []);

        return parent::getLocationPages();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupIDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupIDs', []);

        return parent::getGroupIDs();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', []);

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', []);

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function duplicate($newName, $newSKU = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'duplicate', [$newName, $newSKU]);

        return parent::duplicate($newName, $newSKU);
    }

    /**
     * {@inheritDoc}
     */
    public function generatePage($templateID = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generatePage', [$templateID]);

        return parent::generatePage($templateID);
    }

    /**
     * {@inheritDoc}
     */
    public function updatePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updatePage', []);

        return parent::updatePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageDescription($newDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageDescription', [$newDescription]);

        return parent::setPageDescription($newDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function setPageID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageID', [$cID]);

        return parent::setPageID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function savePageID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'savePageID', [$cID]);

        return parent::savePageID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSold', []);

        return parent::getTotalSold();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectAttributeCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectAttributeCategory', []);

        return parent::getObjectAttributeCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValueObject($ak, $createIfNotExists = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValueObject', [$ak, $createIfNotExists]);

        return parent::getAttributeValueObject($ak, $createIfNotExists);
    }

    /**
     * {@inheritDoc}
     */
    public function getVariationData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariationData', []);

        return parent::getVariationData();
    }

    /**
     * {@inheritDoc}
     */
    public function getVariationLookup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariationLookup', []);

        return parent::getVariationLookup();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($ak, $mode = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', [$ak, $mode]);

        return parent::getAttribute($ak, $mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValue($ak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValue', [$ak]);

        return parent::getAttributeValue($ak);
    }

    /**
     * {@inheritDoc}
     */
    public function clearAttribute($ak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearAttribute', [$ak]);

        return parent::clearAttribute($ak);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($ak, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$ak, $value]);

        return parent::setAttribute($ak, $value);
    }

}
