<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Order;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'oID', 'cID', 'memberCreated', 'oDate', 'pmID', 'pmName', 'smName', 'sInstructions', 'sShipmentID', 'sRateID', 'sCarrier', 'sTrackingID', 'sTrackingCode', 'sTrackingURL', 'sTrackingEstimatedDate', 'oShippingTotal', 'oTax', 'oTaxIncluded', 'oTaxName', 'oTotal', 'transactionReference', 'oPaid', 'oPaidByUID', 'oCancelled', 'oCancelledByUID', 'oRefunded', 'oRefundedByUID', 'oRefundReason', 'oNotes', 'externalPaymentRequested', 'locale', 'userAgent', 'orderItems'];
        }

        return ['__isInitialized__', 'oID', 'cID', 'memberCreated', 'oDate', 'pmID', 'pmName', 'smName', 'sInstructions', 'sShipmentID', 'sRateID', 'sCarrier', 'sTrackingID', 'sTrackingCode', 'sTrackingURL', 'sTrackingEstimatedDate', 'oShippingTotal', 'oTax', 'oTaxIncluded', 'oTaxName', 'oTotal', 'transactionReference', 'oPaid', 'oPaidByUID', 'oCancelled', 'oCancelledByUID', 'oRefunded', 'oRefundedByUID', 'oRefundReason', 'oNotes', 'externalPaymentRequested', 'locale', 'userAgent', 'orderItems'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOrderItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', []);

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerID', [$cID]);

        return parent::setCustomerID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberCreated', []);

        return parent::getMemberCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberCreated($memberCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberCreated', [$memberCreated]);

        return parent::setMemberCreated($memberCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($oDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$oDate]);

        return parent::setDate($oDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodName($pmName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodName', [$pmName]);

        return parent::setPaymentMethodName($pmName);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodID($pmID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodID', [$pmID]);

        return parent::setPaymentMethodID($pmID);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodName($smName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodName', [$smName]);

        return parent::setShippingMethodName($smName);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingInstructions($sInstructions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingInstructions', [$sInstructions]);

        return parent::setShippingInstructions($sInstructions);
    }

    /**
     * {@inheritDoc}
     */
    public function setShipmentID($shipmentID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipmentID', [$shipmentID]);

        return parent::setShipmentID($shipmentID);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipmentID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipmentID', []);

        return parent::getShipmentID();
    }

    /**
     * {@inheritDoc}
     */
    public function getRateID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateID', []);

        return parent::getRateID();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateID($sRateID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateID', [$sRateID]);

        return parent::setRateID($sRateID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarrier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarrier', []);

        return parent::getCarrier();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarrier($sCarrier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarrier', [$sCarrier]);

        return parent::setCarrier($sCarrier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingID', []);

        return parent::getTrackingID();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingID($sTrackingID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingID', [$sTrackingID]);

        return parent::setTrackingID($sTrackingID);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingCode', []);

        return parent::getTrackingCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingCode($sTrackingCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingCode', [$sTrackingCode]);

        return parent::setTrackingCode($sTrackingCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingURL', []);

        return parent::getTrackingURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingURL($sTrackingURL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingURL', [$sTrackingURL]);

        return parent::setTrackingURL($sTrackingURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingEstimatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingEstimatedDate', []);

        return parent::getTrackingEstimatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingEstimatedDate($sTrackingEstimatedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingEstimatedDate', [$sTrackingEstimatedDate]);

        return parent::setTrackingEstimatedDate($sTrackingEstimatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTotal($shippingTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTotal', [$shippingTotal]);

        return parent::setShippingTotal($shippingTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxTotal($taxTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxTotal', [$taxTotal]);

        return parent::setTaxTotal($taxTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxIncluded($taxIncluded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxIncluded', [$taxIncluded]);

        return parent::setTaxIncluded($taxIncluded);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxLabels($taxLabels)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxLabels', [$taxLabels]);

        return parent::setTaxLabels($taxLabels);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionReference($transactionReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionReference', [$transactionReference]);

        return parent::setTransactionReference($transactionReference);
    }

    /**
     * {@inheritDoc}
     */
    public function saveTransactionReference($transactionReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveTransactionReference', [$transactionReference]);

        return parent::saveTransactionReference($transactionReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', []);

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($oPaid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', [$oPaid]);

        return parent::setPaid($oPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidByUID', []);

        return parent::getPaidByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidByUID($oPaidByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidByUID', [$oPaidByUID]);

        return parent::setPaidByUID($oPaidByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelled', []);

        return parent::getCancelled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelled($oCancelled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelled', [$oCancelled]);

        return parent::setCancelled($oCancelled);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelledByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelledByUID', []);

        return parent::getCancelledByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelledByUID($oCancelledByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelledByUID', [$oCancelledByUID]);

        return parent::setCancelledByUID($oCancelledByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefunded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefunded', []);

        return parent::getRefunded();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefunded($oRefunded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefunded', [$oRefunded]);

        return parent::setRefunded($oRefunded);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundedByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundedByUID', []);

        return parent::getRefundedByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundedByUID($oRefundedByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundedByUID', [$oRefundedByUID]);

        return parent::setRefundedByUID($oRefundedByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundReason', []);

        return parent::getRefundReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundReason($oRefundReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundReason', [$oRefundReason]);

        return parent::setRefundReason($oRefundReason);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderID', []);

        return parent::getOrderID();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerID', []);

        return parent::getCustomerID();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDate', []);

        return parent::getOrderDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodID', []);

        return parent::getPaymentMethodID();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodName', []);

        return parent::getPaymentMethodName();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodName', []);

        return parent::getShippingMethodName();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingInstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingInstructions', []);

        return parent::getShippingInstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTotal', []);

        return parent::getShippingTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', []);

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', [$locale]);

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAgent', []);

        return parent::getUserAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAgent($userAgent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAgent', [$userAgent]);

        return parent::setUserAgent($userAgent);
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', [$notes]);

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxes', []);

        return parent::getTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxTotal', []);

        return parent::getTaxTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncludedTaxTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncludedTaxTotal', []);

        return parent::getIncludedTaxTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotal', []);

        return parent::getSubTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionReference', []);

        return parent::getTransactionReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalPaymentRequested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalPaymentRequested', []);

        return parent::getExternalPaymentRequested();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalPaymentRequested($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalPaymentRequested', [$bool]);

        return parent::setExternalPaymentRequested($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomersMostRecentOrderByCID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomersMostRecentOrderByCID', [$cID]);

        return parent::getCustomersMostRecentOrderByCID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributes', []);

        return parent::getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerAddress($customer = NULL, $includeShipping = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerAddress', [$customer, $includeShipping]);

        return parent::addCustomerAddress($customer, $includeShipping);
    }

    /**
     * {@inheritDoc}
     */
    public function completeOrder($transactionReference = NULL, $sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completeOrder', [$transactionReference, $sameRequest]);

        return parent::completeOrder($transactionReference, $sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function completePayment($sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completePayment', [$sameRequest]);

        return parent::completePayment($sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function completePostPaymentProcesses($sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completePostPaymentProcesses', [$sameRequest]);

        return parent::completePostPaymentProcesses($sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function sendNotifications($email = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sendNotifications', [$email]);

        return parent::sendNotifications($email);
    }

    /**
     * {@inheritDoc}
     */
    public function sendOrderReceipt($email = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sendOrderReceipt', [$email]);

        return parent::sendOrderReceipt($email);
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItems($cart, $discountRatio = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItems', [$cart, $discountRatio]);

        return parent::addOrderItems($cart, $discountRatio);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', []);

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function isShippable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippable', []);

        return parent::isShippable();
    }

    /**
     * {@inheritDoc}
     */
    public function updateStatus($status = NULL, $comment = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateStatus', [$status, $comment]);

        return parent::updateStatus($status, $comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHistory', []);

        return parent::getStatusHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHandle', []);

        return parent::getStatusHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectAttributeCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectAttributeCategory', []);

        return parent::getObjectAttributeCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValueObject($ak, $createIfNotExists = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValueObject', [$ak, $createIfNotExists]);

        return parent::getAttributeValueObject($ak, $createIfNotExists);
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscount($discount, $code = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscount', [$discount, $code]);

        return parent::addDiscount($discount, $code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppliedDiscounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppliedDiscounts', []);

        return parent::getAppliedDiscounts();
    }

    /**
     * {@inheritDoc}
     */
    public function saveOrderChoices($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveOrderChoices', [$order]);

        return parent::saveOrderChoices($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressValue($handle, $valuename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressValue', [$handle, $valuename]);

        return parent::getAddressValue($handle, $valuename);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderCompleteDestination($default = '', $locale = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderCompleteDestination', [$default, $locale]);

        return parent::getOrderCompleteDestination($default, $locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($ak, $mode = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', [$ak, $mode]);

        return parent::getAttribute($ak, $mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValue($ak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValue', [$ak]);

        return parent::getAttributeValue($ak);
    }

    /**
     * {@inheritDoc}
     */
    public function clearAttribute($ak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearAttribute', [$ak]);

        return parent::clearAttribute($ak);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($ak, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$ak, $value]);

        return parent::setAttribute($ak, $value);
    }

}
