<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Shipping\Method;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ShippingMethod extends \Concrete\Package\CommunityStore\Src\CommunityStore\Shipping\Method\ShippingMethod implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'smID', 'smtID', 'smtmID', 'smName', 'smDetails', 'smUserGroups', 'smExcludedUserGroups', 'smEnabled', 'smSortOrder', 'smOfferKey'];
        }

        return ['__isInitialized__', 'smID', 'smtID', 'smtmID', 'smName', 'smDetails', 'smUserGroups', 'smExcludedUserGroups', 'smEnabled', 'smSortOrder', 'smOfferKey'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ShippingMethod $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setOfferKey($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferKey', [$key]);

        return parent::setOfferKey($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferKey', []);

        return parent::getOfferKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodTypeID($smt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodTypeID', [$smt]);

        return parent::setShippingMethodTypeID($smt);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodTypeMethodID($smtm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodTypeMethodID', [$smtm]);

        return parent::setShippingMethodTypeMethodID($smtm);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$status]);

        return parent::setEnabled($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDetails($details)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetails', [$details]);

        return parent::setDetails($details);
    }

    /**
     * {@inheritDoc}
     */
    public function setSortOrder($smSortOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortOrder', [$smSortOrder]);

        return parent::setSortOrder($smSortOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', []);

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserGroups($userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserGroups', [$userGroups]);

        return parent::setUserGroups($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludedUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludedUserGroups', []);

        return parent::getExcludedUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcludedUserGroups($userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcludedUserGroups', [$userGroups]);

        return parent::setExcludedUserGroups($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodType', []);

        return parent::getShippingMethodType();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodTypeMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodTypeMethod', []);

        return parent::getShippingMethodTypeMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function getOffers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffers', []);

        return parent::getOffers();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentOffer', []);

        return parent::getCurrentOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', []);

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getSortOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortOrder', []);

        return parent::getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function update($smName, $smEnabled, $smDetails, $smSortOrder, $userGroups, $excludedUserGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$smName, $smEnabled, $smDetails, $smSortOrder, $userGroups, $excludedUserGroups]);

        return parent::update($smName, $smEnabled, $smDetails, $smSortOrder, $userGroups, $excludedUserGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', []);

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodSelector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodSelector', []);

        return parent::getShippingMethodSelector();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageHandle', []);

        return parent::getPackageHandle();
    }

}
