<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductOption;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductOptionItem extends \Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductOption\ProductOptionItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'poiID', 'poID', 'option', 'poiName', 'poiSelectorName', 'pPriceAdjust', 'pWeightAdjust', 'poiSort', 'poiHidden', '' . "\0" . 'Concrete\\Package\\CommunityStore\\Src\\CommunityStore\\Product\\ProductOption\\ProductOptionItem' . "\0" . 'variationoptionitems'];
        }

        return ['__isInitialized__', 'poiID', 'poID', 'option', 'poiName', 'poiSelectorName', 'pPriceAdjust', 'pWeightAdjust', 'poiSort', 'poiHidden', '' . "\0" . 'Concrete\\Package\\CommunityStore\\Src\\CommunityStore\\Product\\ProductOption\\ProductOptionItem' . "\0" . 'variationoptionitems'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductOptionItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setOption($option)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOption', [$option]);

        return parent::setOption($option);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', []);

        return parent::getOption();
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectorName', []);

        return parent::getSelectorName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectorDisplayValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectorDisplayValue', []);

        return parent::getSelectorDisplayValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceAdjustment($discounts = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceAdjustment', [$discounts]);

        return parent::getPriceAdjustment($discounts);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceAdjustment($priceAdjust)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceAdjustment', [$priceAdjust]);

        return parent::setPriceAdjustment($priceAdjust);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightAdjustment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightAdjustment', []);

        return parent::getWeightAdjustment();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightAdjustment($weightAdjust)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightAdjustment', [$weightAdjust]);

        return parent::setWeightAdjustment($weightAdjust);
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionID', []);

        return parent::getOptionID();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSort', []);

        return parent::getSort();
    }

    /**
     * {@inheritDoc}
     */
    public function getHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHidden', []);

        return parent::getHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function isHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHidden', []);

        return parent::isHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function update($name, $sort, $selectorname, $priceAdjust, $weightAdjust, $hidden = false, $persistonly = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$name, $sort, $selectorname, $priceAdjust, $weightAdjust, $hidden, $persistonly]);

        return parent::update($name, $sort, $selectorname, $priceAdjust, $weightAdjust, $hidden, $persistonly);
    }

    /**
     * {@inheritDoc}
     */
    public function save($persistonly = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', [$persistonly]);

        return parent::save($persistonly);
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

}
