<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Order\OrderStatus;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderStatus extends \Concrete\Package\CommunityStore\Src\CommunityStore\Order\OrderStatus\OrderStatus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'osID', 'osHandle', 'osName', 'osInformSite', 'osInformCustomer', 'osIsStartingStatus', 'osSortOrder'];
        }

        return ['__isInitialized__', 'osID', 'osHandle', 'osName', 'osInformSite', 'osInformCustomer', 'osIsStartingStatus', 'osSortOrder'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderStatus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function getHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandle', []);

        return parent::getHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function getReadableHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadableHandle', []);

        return parent::getReadableHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($value = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$value]);

        return parent::setName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformSite', []);

        return parent::getInformSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setInformSite($value = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInformSite', [$value]);

        return parent::setInformSite($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformCustomer', []);

        return parent::getInformCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setInformCustomer($value = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInformCustomer', [$value]);

        return parent::setInformCustomer($value);
    }

    /**
     * {@inheritDoc}
     */
    public function isStartingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStartingStatus', []);

        return parent::isStartingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function update($data = array (
), $ignoreFilledColumns = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$data, $ignoreFilledColumns]);

        return parent::update($data, $ignoreFilledColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray($arr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arr]);

        return parent::setPropertiesFromArray($arr);
    }

}
