<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-04-09T12:00:53+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Tokyo',
];
