<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-04-09T16:31:43+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      markPaid
 * @group     community_store
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'productPublishTarget' => '212',
    'symbol' => '￥',
    'whole' => '.',
    'thousand' => ',',
    'sizeUnit' => 'in',
    'weightUnit' => 'lb',
    'taxName' => 'Tax',
    'guestCheckout' => 'always',
    'customerGroup' => '4',
    'wholesaleCustomerGroup' => '5',
    'digitalDownloadFileSet' => '1',
    'currency' => 'JPY',
    'calculation' => 'extract',
    'vat_number' => false,
    'deliveryInstructions' => null,
    'multiplePackages' => null,
    'notificationemails' => 'sugi@pictron.net',
    'emailalerts' => 'sugi@pictron.net',
    'emailalertsname' => 'sugi@pictron.net',
    'setReplyTo' => false,
    'defaultSingleProductThumbType' => '0',
    'defaultProductListThumbType' => '0',
    'defaultProductModalThumbType' => '0',
    'defaultSingleProductImageWidth' => '720',
    'defaultSingleProductImageHeight' => '720',
    'defaultProductListImageWidth' => '400',
    'defaultProductListImageHeight' => '280',
    'defaultProductModalImageWidth' => '560',
    'defaultProductModalImageHeight' => '999',
    'defaultSingleProductCrop' => '0',
    'defaultProductListCrop' => '0',
    'companyField' => 'off',
    'shoppingDisabled' => '',
    'orderNotesEnabled' => false,
    'placesAPIKey' => '',
    'checkout_scroll_offset' => 0,
    'receiptHeader' => '',
    'receiptFooter' => '',
    'noBillingSave' => '',
    'noShippingSave' => '',
    'noBillingSaveGroups' => '',
    'noShippingSaveGroups' => '',
    'showUnpaidExternalPaymentOrders' => null,
    'numberOfOrders' => '20',
    'download_expiry_hours' => '',
    'logUserAgent' => false,
    'cartMode' => ' ',
    'orderCompleteCID' => '0',
    'invoiceMinimum' => '',
    'invoiceMaximum' => '',
    'paymentInstructions' => '',
    'markPaid' => '0',
];
