<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-04-09T17:16:59+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.full_page_lifetime_value
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1617937253,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.5',
    ],
    'user' => [
        'registration' => [
            'email_registration' => false,
            'type' => 'enabled',
            'captcha' => false,
            'display_username_field' => true,
            'display_confirm_password_field' => true,
            'enabled' => true,
            'validate_email' => false,
            'notification' => null,
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
